### ISSUE TITLE
v0.2.0: Posterior Predictive Simulation

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#3]
## Goal

Features for the v0.2.0 release. These features build out the basic functionality of the v0.1.0 release into a barebones useful package.

## Features

- [x] #47
- [x] Posterior draws: r
- [x] Posterior draws: Rt
- [x] Predict method
- [x] #77
- [x] Print method
- [x]  #40 
- [x] #44
- [x] #82

**Comment by seabbs** [comment]
>  Data simulator with day-of-week, spatial effects, and delay

Personally I would split this into something that increments in complexity across multiple issues/prs

**Comment by zsusswein** [comment]
@seabbs what in here are you thinking about keeping in v0.2.0 vs booting to v0.3.0?

**Comment by seabbs** [comment]
My suggestion is:

`0.3.0`

- [ ] Data simulator: SEIR from specified Rt
- [ ] Data simulator: day-of-week effect
- [ ] Day-of-week effects

`0.4.0`

- [ ] Plot method
- [ ] Benchmarking

`0.5.0`

- [ ] nowcasting simulator
- [ ] Basic nowcasting
- [ ] More flexible nowcasting

`0.6.0`

- Unknown infra fixes and features

`0.7.0`

- [ ] Data simulator: multiple timeseries/partial pooling
- [ ] Preprocessing for multiple groups
- [ ] Modelling multiple groups

I like to try and stick to one major feature per release and to try and tic toc between features and infra releases

**Comment by zsusswein** [comment]
https://github.com/CDCgov/cfa-gam-rt/releases/tag/v0.2.0
